// angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { Transformation } from 'imagekit-javascript/dist/src/interfaces/Transformation';
import { IkUploadComponent } from 'imagekitio-angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'app';
  path = 'default-image.jpg';
  videoPath = 'sample-video.mp4';
  @ViewChild('upload') uploadComponent: IkUploadComponent;

  transformation: Array<Transformation> = [
    {
      height: '200',
      width: '200',
    },
  ];

  flexibleTransformationOne: Array<Transformation> = [
    {
      height: '300',
      width: '300',
    },
  ];

  flexibleTransformationTwo: Array<Transformation> = [
    {
      height: '200',
      width: '200',
    },
  ];

  videoAdvanceTransformation: Array<Transformation> = [
    {
      height: '200',
      width: '600',
      b: '5_red',
      q: '95',
    },
  ];

  lqipOne = { active: true, quality: 20, blur: 10 };
  lqipTwo = { active: true, quality: 20, blur: 30 };

  lazyload = 'lazy';

  uploadedImageSource = 'https://ik.imagekit.io/demo/default-image.jpg';
  uploadErrorMessage = '';

  authenticator = async () => {
    try {
      // You can pass headers as well and later validate the request source in the backend, or you can use headers for any other use case.
      const response = await fetch('http://localhost:3000/auth');

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(
          `Request failed with status ${response.status}: ${errorText}`
        );
      }

      const data = await response.json();
      const { signature, expire, token } = data;
      return { signature, expire, token };
    } catch (error) {
      throw new Error(`Authentication request failed: ${error.message}`);
    }
  };

  applyImgTransformationOne(res) {
    this.flexibleTransformationOne = [
      {
        height: '200',
        width: '600',
        radius: 'max',
      },
      {
        height: '200',
        width: '200',
        rotate: '180',
      },
      {
        raw: 'l-text,i-TEST,fs-50,co-10C0F0,l-end',
      },
    ];
  }

  applyImgTransformationTwo(res) {
    this.flexibleTransformationTwo = [
      {
        height: '200',
        width: '200',
        radius: 'max',
      },
    ];
  }

  validateFileFunction(res: any) {
    console.log('validating');
    if (res.size < 1000000) {
      // Less than 1mb
      return true;
    }
    return false;
  }

  onUploadStartFunction(res: any) {
    console.log('onUploadStart');
  }

  onAbortFunction() {
    this.uploadComponent && this.uploadComponent.abort();
  }

  onUploadProgressFunction(res: any) {
    console.log('progressing');
  }

  handleUploadSuccess(res) {
    console.log('File upload success with response: ', res);
    console.log(res.$ResponseMetadata.statusCode); // 200
    console.log(res.$ResponseMetadata.headers); // headers
    this.uploadedImageSource = res.url;
  }

  handleUploadError(err) {
    console.log('There was an error in upload: ', err);
    this.uploadErrorMessage = 'File upload failed.';
  }
}

<div className="App">
  <h1>Hi! This is an ImageKit Angular SDK Demo!</h1>
  <p>Video Element</p>
  <ik-video
    urlEndpoint="https://ik.imagekit.io/demo/"
    class='ikvideo-default'
    [path]='videoPath'
    [transformation]='transformation'
    controls=true>
  </ik-video>

  <p>Video with some advance transformation</p>
  <ik-video
    urlEndpoint="https://ik.imagekit.io/demo/"
    class='ikvideo-with-tr'
    [path]='videoPath'
    [transformation]='videoAdvanceTransformation'
    controls=true>
  </ik-video>
  <p>Dynamic transformation update directly using IKImage</p>
  <ik-image
        id="img-transformation-direct"
        class="img-transformation-direct"
        path={{path}}
        urlEndpoint="https://ik.imagekit.io/demo/"
        [transformation]="flexibleTransformationOne"
        [loading]="lazyload">
  </ik-image>
  <div>
    <p>Click here to apply transformations on the above image</p>
    <button
      class="btn-to-change-tr-direct"
      (click)="applyImgTransformationOne($event)">
      Click to apply transformations
    </button>
  </div>
  <br />
  <p>Lazy loading image</p>
  <ik-image
        class='lazyload'
        path={{path}}
        urlEndpoint="https://ik.imagekit.io/demo/"
        [transformation]="transformation"
        [loading]="lazyload">
  </ik-image>
  <p>Transformation - height and width manipulation</p>
  <ik-image 
    urlEndpoint="https://ik.imagekit.io/demo/"
    class='img-transformation' 
    [path]=path
    [transformation]='flexibleTransformationTwo'>
  </ik-image>
  <div>
    <p>Click here to apply max radius on above image </p>
    <button
      class='btn-to-change-tr'
      (click)='applyImgTransformationTwo($event)'>
      Click to apply radius
    </button>
  </div>
  <br />
  <p>Progressive image loading without lazy loading</p>
  <ik-image
        class='lqip'
        path={{path}}
        urlEndpoint="https://ik.imagekit.io/demo/"
        [transformation]="transformation"
        [lqip]="lqipOne">
  </ik-image>
  <p>Progressive image loading with lazy loading</p>
  <ik-image
        class='lazyload-lqip'
        path={{path}}
        urlEndpoint="https://ik.imagekit.io/demo/"
        [transformation]="transformation"
        [loading]="lazyload"
        [lqip]="lqipTwo">
  </ik-image>
  <p>Adding text overlay to image</p>
  <ik-image
    class='lazyload-lqip'
    path={{path}}
    urlEndpoint="https://ik.imagekit.io/demo/"
    [transformation]='[{ "width": "300", "height": "300" },{ "raw": "l-text,i-Imagekit,rt-90,co-0651D5,fs-50,l-end" }]'>
  </ik-image>
  <p>Upload</p>
  <p>To use this funtionality please remember to setup the server</p>
  <ik-upload 
    #upload
    fileName="test.jpg" 
    [tags]='["sample-tag1", "sample-tag2"]'
    customCoordinates="10,10,10,10"
    [isPrivateFile]="false"
    [useUniqueFileName]="true" 
    [responseFields]='["tags"]'
    folder="/sample-folder"
    (onError)="handleUploadError($event)"
    (onSuccess)="handleUploadSuccess($event)" 
    [validateFile]="validateFileFunction"
    [onUploadStart]="onUploadStartFunction"
    [onUploadProgress]="onUploadProgressFunction"
    [authenticator]="authenticator"
    [transformation]='{ "pre": "l-text,i-Imagekit,fs-50,l-end", "post": [{type: "transformation", value: "w-100"}]}'
    class="file-upload-ik">
  </ik-upload>
  <button (click)="onAbortFunction()">Abort</button>
  <p>Your above uploaded file will appear here </p>
  <ik-image 
    [src]="uploadedImageSource"
    class="uploaded-img-ik">
  </ik-image>

  <p>Upload invalid file</p>
  <ik-upload
    class="file-upload-error"
    fileName="test-fail.jpg"
    folder="/sample-folder"
    (onError)="handleUploadError($event)"
    (onSuccess)="handleUploadSuccess($event)">
  </ik-upload>

  <p style="color:red" class="upload-error-ik">
    {{uploadErrorMessage}}
  </p>

  <p>Upload with custom button</p>
  <ik-upload 
    (onSuccess)="handleUploadSuccess($event)"
    (onError)="handleUploadError($event)"
    [buttonRef] = 'myBtn'
    [authenticator]="authenticator"
    >
  </ik-upload>
  <button #myBtn type="button" style="color:blue">
    <span>Upload</span>
  </button>
</div>

// react/src/App.js
import React, { useRef } from 'react';
import './App.css';
import { IKContext, IKImage, IKUpload, IKVideo } from 'imagekitio-react';

const publicKey = '<YOUR_IMAGEKIT_PUBLIC_KEY>';
const urlEndpoint = '<YOUR_IMAGEKIT_URL_ENDPOINT>';
const authenticationEndpoint = 'http://localhost:3001/auth';
const videoUrlEndpoint = 'https://ik.imagekit.io/demo/';
const videoPath = "sample-video.mp4";

const onError = err => {
  console.log("Error", err);
};

const onSuccess = res => {
  console.log("Success", res);
};

const onUploadProgress = progress => {
  console.log("Progress", progress);
};

const onUploadStart = evt => {
  console.log("Start", evt);
};

const authenticator = async () => {
  try {
    // You can pass headers as well and later validate the request source in the backend, or you can use headers for any other use case.
    const response = await fetch(authenticationEndpoint);

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Request failed with status ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const { signature, expire, token } = data;
    return { signature, expire, token };
  } catch (error) {
    throw new Error(`Authentication request failed: ${error.message}`);
  }
};

function App() {
  const ikUploadRefTest = useRef(null);
  return (
    <div className="App">
      <IKContext
        publicKey={publicKey}
        urlEndpoint={urlEndpoint}
        authenticator={authenticator}
      >
        <h1>ImageKit React quick start</h1>
        <h2>File upload</h2>
        <IKUpload
          fileName="test-upload.png"
          onError={onError}
          onSuccess={onSuccess}
        />
        <h2>Advanced file upload</h2>
        <IKUpload
          fileName="test-upload.jpg"
          tags={["sample-tag1", "sample-tag2"]}
          customCoordinates={"10,10,10,10"}
          isPrivateFile={false}
          useUniqueFileName={true}
          responseFields={["tags"]}
          folder={"/sample-folder"}
          validateFile={file => file.size < 2000000}
          extensions={[{
            "name": "remove-bg",
            "options": {
              "add_shadow": true,
              "semitransparency":false
            },
          }]}
          webhookUrl="https://www.example.com/imagekit-webhook" // replace with your webhookUrl
          overwriteFile={true}
          overwriteAITags={true}
          overwriteTags={true}
          overwriteCustomMetadata={true}
          // customMetadata={{
          //   "brand": "Nike",
          //   "color": "red",
          // }}
          onError={onError}
          onSuccess={onSuccess}
          onUploadProgress={onUploadProgress}
          onUploadStart={onUploadStart}
          // style={{display: 'none'}} // hide the default input and use the custom upload button
          ref={ikUploadRefTest}
          transformation={{ pre: "l-text,i-Imagekit,fs-50,l-end", post: [{ type: "transformation", value: "w-100" }] }}
        />
        <p>Custom Upload Button</p>
        {ikUploadRefTest && <button onClick={() => ikUploadRefTest.current.click()}>Upload</button>}
        <p>Abort upload request</p>
        {ikUploadRefTest && <button onClick={() => ikUploadRefTest.current.abort()}>Abort request</button>}
      </IKContext>

      <IKContext urlEndpoint={urlEndpoint}>
        <h2>Rendering image</h2>
        <IKImage path="default-image.jpg" width="400" />

        <h2>Loading image from an absolute path</h2>
        <IKImage
          src="https://ik.imagekit.io/demo/default-image.jpg"
          width="400"
        />

        <h2>Height and width manipulation</h2>
        <IKImage
          path="default-image.jpg"
          transformation={[{
            height: 200,
            width: 200
          }]}
        />

        <h2>Crop mode</h2>
        <IKImage
          path="default-image.jpg"
          transformation={[{
            height: 300,
            width: 200,
            cropMode: 'extract',
          }]}
        />

        <h2>Quality manipulation</h2>
        <IKImage
          path="default-image.jpg"
          transformation={[{ quality: 10 }]}
          width="400"
        />

        <h2>Chained transformation</h2>
        <h3>Step 1: Resized and cropped</h3>
        <IKImage
          path="default-image.jpg"
          transformation={[{
            height: 300,
            width: 200
          }]}
        />

        <h3>Step 2: Resized and cropped, then rotated</h3>
        <IKImage
          path="default-image.jpg"
          transformation={[{
            height: 300,
            width: 200,
          }, {
            rt: 90,
          }]}
        />

        <h3>Step 3: Rotated, then resized and cropped</h3>
        <IKImage
          path="default-image.jpg"
          transformation={[{
            rt: 90,
          }, {
            height: 300,
            width: 200,
          }]}
        />

        <h2>Adding text overlay to image</h2>
        <IKImage
          path="default-image.jpg"
          transformation={[{
            height: 300,
            width: 300,
            raw: "l-text,i-Imagekit,rt-90,co-0651D5,fs-50,l-end"
          }]}
        />

        <h2>Lazy loading images</h2>
        <IKImage
          path="default-image.jpg"
          transformation={[{ height: 300, width: 400 }]}
          loading="lazy"
          height="300"
          width="400"
        />

        <h2>Blurred image placeholder</h2>
        <IKImage
          path="default-image.jpg"
          lqip={{ active: true, quality: 20 }}
          width="400"
        />

        <h3>Combining lazy loading with low-quality placeholders</h3>
        <IKImage
          path="default-image.jpg"
          transformation={[{ height: 300, width: 400 }]}
          lqip={{ active: true }}
          loading="lazy"
          height="300"
          width="400"
        />
      </IKContext>
      <IKContext publicKey={publicKey} authenticator={authenticator} urlEndpoint={videoUrlEndpoint}>
        <h2>Video Element</h2>
        <IKVideo
          className='ikvideo-default'
          path={videoPath}
          transformation={[{ height: 200, width: 200 }]}
          controls={true}
        />

        <br />
        <h2>Video with some advance transformation</h2>
        <IKVideo
          className='ikvideo-with-tr'
          path={videoPath}
          transformation={[{ height: 200, width: 600, b: '5_red', q: 95 }]}
          controls={true}
        />
      </IKContext>
    </div>
  );
}

export default App;
